;;; Exercise 4.40

;;; Before requirement: 5^5 = 3,125
;;; After requirement: 5! = 120

(define (multiple-dwelling)
  (let ((fletcher (amb 1 2 3 4 5)))
    (require (not (= fletcher 5)))
    (require (not (= fletcher 1)))
    (let ((cooper (amb 1 2 3 4 5)))
      (require (not (= cooper 1)))
      (require (not (= (abs (- fletcher cooper)) 1)))
      (require (not (= fletcher cooper)))
      (let ((miller (amb 1 2 3 4 5)))
	(require (> miller cooper))
	(require (and (not (= miller fletcher))
		      (not (= miller cooper))))
	(let ((smith (amb 1 2 3 4 5)))
	  (require (not (= (abs (- smith fletcher)) 1)))
	  (require (and (not (= smith miller))
			(not (= smith cooper))
			(not (= smith fletcher))))
	  (let ((baker (amb 1 2 3 4 5)))
	    (require (not (= baker 5)))
	    (require (and (not (= baker smith))
			  (not (= baker miller))
			  (not (= baker cooper))
			  (not (= baker fletcher))))
	    (list (list 'baker baker)
		  (list 'cooper cooper)
		  (list 'fletcher fletcher)
		  (list 'miller miller)
		  (list 'smith smith))))))))
